export const resourceCenters = [
  {
    key: "learning",
    label: "学习中心",
    iconType: "book",
    tone: "dusk",
    gradient: "linear-gradient(135deg, #243958 0%, #3f6492 100%)",
    eyebrow: "Learning Hub",
    title: "科研资料与方法库",
    subtitle: "把教程、规范、论文和常用工具沉淀为团队可复用的知识资产。",
    datasetId: 300,
    version: "v1",
    categoryLabel: "资料类型",
    categories: ["全部", "教程文档", "学术论文", "规范手册", "工具软件", "数据集说明"],
    sampleItems: [
      {
        title: "AIS 数据清洗与匹配指南",
        summary: "涵盖轨迹去噪、坐标修正、时间归并与多源匹配的标准流程。",
        category: "教程文档",
        author: "方法组",
        updatedAt: "2026-03-18T10:20:00",
        tags: ["Python", "轨迹", "清洗"],
      },
      {
        title: "实验室数据命名规范 2.1",
        summary: "统一版本号、文件夹层级、标签和元数据字段，便于长期维护。",
        category: "规范手册",
        author: "平台组",
        updatedAt: "2026-02-11T09:00:00",
        tags: ["规范", "版本", "元数据"],
      },
      {
        title: "库区社会调查问卷设计指引",
        summary: "包含样本量计算、量表设计与回收质量控制建议。",
        category: "教程文档",
        author: "调查组",
        updatedAt: "2026-01-26T14:35:00",
        tags: ["问卷", "方法", "调查"],
      },
    ],
    extraFields: [
      { key: "resourceType", label: "资料类型", type: "select", options: ["教程文档", "学术论文", "规范手册", "工具软件", "数据集说明", "其他"] },
    ],
  },
  {
    key: "code",
    label: "程序中心",
    iconType: "code",
    tone: "aurora",
    gradient: "linear-gradient(135deg, #0c4454 0%, #1a7c8d 100%)",
    eyebrow: "Code Hub",
    title: "算法项目与复现实验",
    subtitle: "统一管理项目说明、运行环境、数据依赖和成果复现信息。",
    datasetId: 100,
    version: "v1",
    categoryLabel: "语言栈",
    categories: ["全部", "Python", "JavaScript", "MATLAB", "R", "Java"],
    sampleItems: [
      {
        title: "三峡船舶拥堵预测模型",
        summary: "结合 AIS 轨迹与气象数据的时序预测项目，支持多步前瞻。",
        category: "Python",
        author: "算法组",
        updatedAt: "2026-04-02T11:30:00",
        tags: ["LSTM", "AIS", "预测"],
      },
      {
        title: "移民生计仿真平台前端",
        summary: "用于政策情景演示的交互式可视化界面与配置系统。",
        category: "JavaScript",
        author: "产品组",
        updatedAt: "2026-03-22T18:10:00",
        tags: ["React", "可视化", "仿真"],
      },
      {
        title: "生态价值核算工具箱",
        summary: "把指标标准化、加权评分与空间映射流程封装成可复用脚本。",
        category: "MATLAB",
        author: "水资源组",
        updatedAt: "2026-02-07T15:45:00",
        tags: ["核算", "空间分析", "工具箱"],
      },
    ],
    extraFields: [
      { key: "language", label: "主要语言", type: "select", options: ["Python", "JavaScript", "MATLAB", "R", "Java", "其他"] },
      { key: "repoUrl", label: "代码仓库地址", type: "text", placeholder: "https://..." },
    ],
  },
  {
    key: "survey",
    label: "问卷中心",
    iconType: "survey",
    tone: "copper",
    gradient: "linear-gradient(135deg, #7a4117 0%, #cc7a28 100%)",
    eyebrow: "Survey Hub",
    title: "调查问卷与样本资料",
    subtitle: "围绕区域调查、样本设计、回收文件和说明材料建立标准化归档。",
    datasetId: 200,
    version: "v1",
    categoryLabel: "区域范围",
    categories: ["全部", "三峡库区", "南水北调", "金沙江下游", "长江经济带", "其他区域"],
    sampleItems: [
      {
        title: "库区移民家庭生计问卷 2025",
        summary: "覆盖收入结构、资产配置、教育、医疗与社会支持五个维度。",
        category: "三峡库区",
        author: "调查组",
        updatedAt: "2026-04-10T08:30:00",
        tags: ["生计", "家庭", "样本"],
      },
      {
        title: "游客满意度抽样调查",
        summary: "用于文旅实验室游客服务质量评估与营销复盘。",
        category: "长江经济带",
        author: "文旅组",
        updatedAt: "2026-03-03T13:20:00",
        tags: ["旅游", "满意度", "抽样"],
      },
      {
        title: "基层治理协同调查模板",
        summary: "适用于部门协作、服务响应和公共资源配置研究。",
        category: "其他区域",
        author: "治理组",
        updatedAt: "2026-01-15T10:00:00",
        tags: ["治理", "协同", "模板"],
      },
    ],
    extraFields: [
      { key: "region", label: "调查区域", type: "select", options: ["三峡库区", "南水北调", "金沙江下游", "长江经济带", "其他区域"] },
      { key: "surveyYear", label: "调查年份", type: "text", placeholder: "例如 2026" },
      { key: "sampleSize", label: "样本量", type: "text", placeholder: "例如 500" },
    ],
  },
];

export const resourceCenterMap = Object.fromEntries(resourceCenters.map((item) => [item.key, item]));
