export const resourceCenters = [
  {
    key: "learning",
    label: "学习中心",
    iconType: "book",
    tone: "dusk",
    gradient: "linear-gradient(135deg, #243958 0%, #3f6492 100%)",
    eyebrow: "Learning Hub",
    title: "论文、链接与学习资料共享区",
    subtitle: "所有已登录用户都可以提交论文、教程、方法链接或工具资料，管理员审核通过后公开展示。",
    datasetId: 300,
    version: "v1",
    categoryLabel: "资料类型",
    categories: ["全部", "学术论文", "教程资料", "方法工具", "数据说明", "课程链接", "其他"],
    sampleItems: [],
    extraFields: [
      {
        key: "resourceType",
        label: "资料类型",
        type: "select",
        options: ["学术论文", "教程资料", "方法工具", "数据说明", "课程链接", "其他"],
      },
    ],
  },
  {
    key: "code",
    label: "程序中心",
    iconType: "code",
    tone: "aurora",
    gradient: "linear-gradient(135deg, #0c4454 0%, #1a7c8d 100%)",
    eyebrow: "Code Hub",
    title: "算法项目与复现实验",
    subtitle: "统一管理项目说明、运行环境、数据依赖和成果复现信息。",
    datasetId: 100,
    version: "v1",
    categoryLabel: "语言栈",
    categories: ["全部", "Python", "JavaScript", "MATLAB", "R", "Java"],
    sampleItems: [],
    extraFields: [
      { key: "language", label: "主要语言", type: "select", options: ["Python", "JavaScript", "MATLAB", "R", "Java", "其他"] },
      { key: "repoUrl", label: "代码仓库地址", type: "text", placeholder: "https://..." },
    ],
  },
  {
    key: "survey",
    label: "问卷中心",
    iconType: "survey",
    tone: "copper",
    gradient: "linear-gradient(135deg, #7a4117 0%, #cc7a28 100%)",
    eyebrow: "Survey Hub",
    title: "调查问卷与样本资料",
    subtitle: "围绕区域调查、样本设计、回收文件和说明材料建立标准化归档。",
    datasetId: 200,
    version: "v1",
    categoryLabel: "区域范围",
    categories: ["全部", "三峡库区", "南水北调", "金沙江下游", "长江经济带", "其他区域"],
    sampleItems: [],
    extraFields: [
      { key: "region", label: "调查区域", type: "select", options: ["三峡库区", "南水北调", "金沙江下游", "长江经济带", "其他区域"] },
      { key: "surveyYear", label: "调查年份", type: "text", placeholder: "例如 2026" },
      { key: "sampleSize", label: "样本量", type: "text", placeholder: "例如 500" },
    ],
  },
];

export const resourceCenterMap = Object.fromEntries(resourceCenters.map((item) => [item.key, item]));
