export const labs = [
  {
    key: "lab-water",
    label: "水资源智慧治理与生态价值实现",
    shortLabel: "水资源实验室",
    iconType: "water",
    tone: "ocean",
    gradient: "linear-gradient(135deg, #114b72 0%, #0b6aa8 55%, #37a9d5 100%)",
    image: "/shui.jpg",
    badge: "智慧流域",
    summary: "聚焦三峡与长江经济带的水资源配置、生态调度、数字孪生和价值转化，构建从监测到决策的闭环能力。",
    mission: "用数据驱动流域治理，让生态价值可感知、可量化、可运营。",
    stats: [
      { label: "监测站点", value: "200+", iconType: "monitor" },
      { label: "专题数据集", value: "38", iconType: "database" },
      { label: "调度模型", value: "12", iconType: "chart" },
    ],
    pillars: [
      { title: "流域数字孪生", text: "整合水文、遥感与设施运行数据，实现实时感知与趋势模拟。", iconType: "layers" },
      { title: "生态价值评估", text: "打通生态修复、碳汇和空间价值指标，支撑治理收益分析。", iconType: "spark" },
      { title: "协同决策引擎", text: "面向防洪、供水、生态调度的多目标分析与策略推荐。", iconType: "target" },
    ],
    platforms: ["流域监测总览平台", "生态修复评估看板", "调度情景推演系统"],
    highlights: ["跨源监测融合", "防洪生态双目标", "空间价值映射"],
  },
  {
    key: "lab-migrant",
    label: "移民可持续生计与社会模拟",
    shortLabel: "移民生计实验室",
    iconType: "users",
    tone: "violet",
    gradient: "linear-gradient(135deg, #40377d 0%, #6d5ad3 55%, #8d7df0 100%)",
    image: "/ym.jpg",
    badge: "社会模拟",
    summary: "围绕库区移民与区域发展，研究生计韧性、社会网络、政策协同和群体行为演化。",
    mission: "把复杂的人群迁移和社会变化，转化为可推演、可解释的政策支持模型。",
    stats: [
      { label: "问卷样本", value: "10k+", iconType: "survey" },
      { label: "仿真场景", value: "24", iconType: "layers" },
      { label: "政策主题", value: "18", iconType: "shield" },
    ],
    pillars: [
      { title: "生计韧性识别", text: "刻画家庭资产、就业机会、社会支持和风险暴露的变化路径。", iconType: "shield" },
      { title: "社会行为模拟", text: "构建群体迁移、协作和政策反馈的多主体仿真体系。", iconType: "users" },
      { title: "政策协同评估", text: "把扶持、安置、教育和产业政策纳入同一分析框架。", iconType: "chart" },
    ],
    platforms: ["移民生计画像平台", "多主体社会模拟器", "政策协同评估中心"],
    highlights: ["家庭资产画像", "多主体仿真", "政策反馈分析"],
  },
  {
    key: "lab-shipping",
    label: "三峡通航智能调度与数字决策",
    shortLabel: "智慧通航实验室",
    iconType: "shipping",
    tone: "aurora",
    gradient: "linear-gradient(135deg, #0b4256 0%, #16657b 52%, #30a98e 100%)",
    image: "/th.jpg",
    badge: "智能调度",
    summary: "聚焦三峡通航、港航联动与绿色航运，研究船舶行为识别、拥堵预测与调度优化。",
    mission: "让航运系统更高效、更绿色、更有弹性。",
    stats: [
      { label: "AIS 轨迹", value: "1.2亿+", iconType: "data" },
      { label: "调度策略", value: "32", iconType: "target" },
      { label: "仿真时段", value: "365天", iconType: "monitor" },
    ],
    pillars: [
      { title: "航运态势感知", text: "结合 AIS、气象和闸坝数据，形成细粒度通航态势底图。", iconType: "globe" },
      { title: "拥堵与风险预测", text: "提前发现高峰拥堵、异常行为和潜在安全风险。", iconType: "shield" },
      { title: "绿色调度优化", text: "兼顾效率、能耗和排放约束，优化调度策略。", iconType: "spark" },
    ],
    platforms: ["通航态势中枢", "船舶轨迹算法平台", "绿色调度决策台"],
    highlights: ["船舶行为识别", "拥堵预测", "排放约束优化"],
  },
  {
    key: "lab-culture",
    label: "三峡文化与旅游数智化管理",
    shortLabel: "文旅数智实验室",
    iconType: "culture",
    tone: "copper",
    gradient: "linear-gradient(135deg, #6d3718 0%, #a95722 50%, #d9822b 100%)",
    image: "/wh.png",
    badge: "数字文旅",
    summary: "融合内容生成、游客画像、景区运营和数字孪生，推进三峡文旅的品牌传播与智能管理。",
    mission: "让文化内容更生动，让游客服务更精准，让景区管理更聪明。",
    stats: [
      { label: "游客标签", value: "120+", iconType: "users" },
      { label: "内容资产", value: "500+", iconType: "book" },
      { label: "数字场景", value: "16", iconType: "layers" },
    ],
    pillars: [
      { title: "游客精准画像", text: "基于搜索、票务、位置与互动数据打造多维用户画像。", iconType: "users" },
      { title: "AIGC 内容生产", text: "把文化叙事、导览内容和多媒体素材高效生产出来。", iconType: "spark" },
      { title: "景区运营决策", text: "面向客流、服务、营销和舆情建立运营洞察闭环。", iconType: "chart" },
    ],
    platforms: ["文旅内容中台", "游客画像引擎", "景区数智运营看板"],
    highlights: ["AIGC 导览", "数字孪生景区", "精细化运营"],
  },
];

export const labMap = Object.fromEntries(labs.map((lab) => [lab.key, lab]));
